# Model Configuration
model:
    arch: frrnB

# Data Configuration
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 256
    img_cols: 256
    path: D:\Dataset\cityscapes\

# Training Configuration
training:
    n_workers: 1
    train_iters: 90000
    batch_size: 2
    val_interval: 500
    print_interval: 10
    loss:
        name: cross_entropy

    # Optmizer Configuration
    optimizer:
        name: sgd
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: 0.99
       
    # Augmentations Configuration
    augmentations:
        brightness: 0.5                                #[brightness varied in 1-x to 1+x]
        hflip: 0.5                                     #[flip horizontally with chance p]

    # LR Schedule Configuration
    lr_schedule:
        name: poly_lr
        max_iter: 90000
    # Resume from checkpoint  
    resume: None
